version: 2
updates:
  # ✅ Python Dependencies (Django, Flask, etc.)
  - package-ecosystem: "pip"
    directory: "/"  # Change if dependencies are inside a subfolder
    schedule:
      interval: "weekly"  # Can be "daily" or "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "django"  # Example: If you want to lock a specific version

  # ✅ JavaScript Dependencies (If using any frontend or Node.js tools)
  - package-ecosystem: "npm"
    directory: "/"  # Change to the folder containing package.json (if applicable)
    schedule:
      interval: "weekly"

  # ✅ GitHub Actions Dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
