# Generated by Django 5.1.7 on 2025-03-28 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("barcode", models.CharField(max_length=50, unique=True)),
                (
                    "book_type",
                    models.CharField(
                        choices=[
                            ("textbook", "Textbook"),
                            ("reference", "Reference Book"),
                            ("magazine", "Magazine"),
                            ("novel", "Novel"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("publisher", models.CharField(max_length=200)),
                (
                    "publication_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2024),
                        ]
                    ),
                ),
                ("edition", models.CharField(blank=True, max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("available_quantity", models.PositiveIntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title", "author"],
                "indexes": [
                    models.Index(fields=["isbn"], name="models_new__isbn_3e3b5c_idx"),
                    models.Index(
                        fields=["barcode"], name="models_new__barcode_c763a0_idx"
                    ),
                    models.Index(
                        fields=["title", "author"], name="models_new__title_2ed6b5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField(blank=True)),
                ("principal_name", models.CharField(max_length=100)),
                ("established_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school_logos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="models_new__code_4db844_idx")
                ],
            },
        ),
    ]
